#!/bin/bash

printf "# HackerRank - My Solutions\n\n" > README.md
printf "Number of solutions in each category:\n\n" >> README.md

total=0

for d in */
do
    dir=${d%*/}
    count=$(find $dir -maxdepth 1 -type f | wc -l)
    total=$((total+count))
    printf "$dir: $count\n\n" >> README.md
done

printf "**Total: $total**\n\n" >> README.md

