#!/bin/bash

printf "# HackerRank - My Solutions\n\n" > README.md
printf "Number of solutions in each category:\n\n" >> README.md

du ./*/ --inodes -d 1 \
    | sort -nr \
    | awk -F'\t' \ '
        {
            sum+=($1-1)
            sub("^./", "", $2)
            sub("/$", "", $2)
            print $2 ": " $1-1 "\n"
        }
        END {print "**Total: " sum "**"}' \
    >> README.md

